apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-nginx
  namespace: default
spec:
  chart:
    spec:
      chart: nginx-helm
      version: 0.1.1
      sourceRef:
        kind: HelmRepository
        name: mycharts
        namespace: default
  interval: 5m
  values:
    replicaCount: 1
    image:
      repository: nginx
      tag: stable
    secret:
      username: admin
      password: changeme