apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tiny-app
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "15.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    replicaCount: 1
    extraEnvVars:
      - name: APP_USERNAME
        valueFrom:
          secretKeyRef:
            name: demo-creds
            key: username
      - name: APP_PASSWORD
        valueFrom:
          secretKeyRef:
            name: demo-creds
            key: password